# Generated by Django 3.1.4 on 2021-01-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog_text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
